### ISSUE TITLE
PHP怎么验签？

### ISSUE THREAD

**Issue by mfkwvf** [lipingruan/fucking-util-signature-all#3]
前端私钥加密：
let rsa = new Signature.RSA ( );
// 设置公私钥
rsa.setPrivateKey ( this.privateKey );
let unsigned = 'h';
// 字符串签名
let sign = rsa.sign ( unsigned, 'base64'/*buffer|binary|hex*/ );

后端使用phpseclib

$rsa = new RSA();
$rsa->loadKey($key); 
echo $rsa->verify('h', base64_decode($data['sign'])) ? 'verified' : 'unverified';

结果永远是unverified，打印出来看，同一对密钥前端加密的值跟后端加密的值不一致。
望大佬指教！！

**Comment by mfkwvf** [comment]
解决了~

**Comment by lipingruan** [comment]
好的，有需要改进的地方可以说。


 

-------- 原始邮件 --------
发件人：zhou jian <notifications@github.com>
时间：2019年9月4日 18:28
收件人：lipingruan/fucking-util-signature-all <fucking-util-signature-all@noreply.github.com>
抄送：Subscribed <subscribed@noreply.github.com>
主题：Re: [lipingruan/fucking-util-signature-all] PHP怎么验签？ (#3)
