### ISSUE TITLE
uniapp不支持

### ISSUE THREAD

**Issue by seho-dev** [lipingruan/fucking-util-signature-all#9]
uniapp的v3引擎；
不知道这个库是不是核心是node-rsa
我用此库报了同样的错误
`reportJSException >>>> exception function:createInstanceContext, exception:white screen cause create instanceContext failed,check js stack ->Exception: Error: Secure random number generation is not supported by this browser.`

值得考察的事情是，无论是编译此库还是编译node-rsa库都遇到了require变量找不到的方法，后来在vue文件中编译才没有这样的错误，所以问一下作者这个解决办法，如何在js中require包

还有就是上面代码提到的这个问题

到处找不到作者的微信或者联系方式，这个加密对我很重要，劳驾作者大大加一下我的微信

微信：meng99huan

**Comment by seho-dev** [comment]
我总结了一下：
uniapp现在有3种编译模式，一种是非自定义组件编译模式（就是webview渲染引擎）
一种是自定义组件渲染
还有一种是v3引擎，这个是性能最好的

但是现在由于生成随机加密数的api在v3和自定义组件渲染模式中不支持，所以非对称加密是不可取的目前，看看有没有其他的办法和解决方案

https://ask.dcloud.net.cn/question/73832
https://ask.dcloud.net.cn/question/714

**Comment by seho-dev** [comment]
如果为了加密换取整个app的性能体验，这不值当，所以看看有没有两全其美的办法

**Comment by lipingruan** [comment]
Nvue使用本库有特殊方法: [你好,关于Nvue里面没办法使用](https://github.com/lipingruan/fucking-util-signature-all/issues/5)

**Comment by JavinYang** [comment]
我很奇怪为什么v3使用这个库会出错是什么导致的？官方说4月份除了v3不再支持自定义组建模式，如果这个库不能用基本上等于宣判死刑。

**Comment by lipingruan** [comment]
> 我很奇怪为什么v3使用这个库会出错是什么导致的？官方说4月份除了v3不再支持自定义组建模式，如果这个库不能用基本上等于宣判死刑。

我一直都在用啊, V3版本也没问题, 建议你升级最新版本HBuilder, 我现在用的2.6.5;
如果是Nvue的话我上面给出了解决办法.

**Comment by lipingruan** [comment]
@JavinYang

**Comment by JavinYang** [comment]
> @JavinYang

升级HBuild后可以了
